[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "slack-delex"
version = "0.1.0"

[dependencies]
clap = "2.29.0"
dotenv = "0.10.1"
failure = "0.1.1"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
slack_api = "0.19.0"
