[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "slack-delex"
version = "0.1.0"

[dependencies]
clap = "^2.32.0"
dotenv = "^0.13.0"
failure = "^0.1.1"
serde = "^1.0.70"
serde_derive = "^1.0.70"
serde_json = "^1.0.22"
slack_api = "^0.20.0"
