[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "slack-delex"
version = "0.1.0"

[dependencies]
clap = "^2.31.2"
dotenv = "^0.11.0"
failure = "^0.1.1"
serde = "^1.0.58"
serde_derive = "^1.0.58"
serde_json = "^1.0.17"
slack_api = "^0.19.0"
